import { useEffect, useState } from 'react'
import { ArrowLeft, RotateCcw, Trophy } from 'lucide-react'
import { localRepository } from '../../data/db'
import type { GameProgress } from '../../domain/game'
import { isSolved, moveTile, shuffleBoard, type SliderBoard } from './engine'
import './slider.css'
interface State { board: SliderBoard; moves: number }
const fresh=():State=>({board:shuffleBoard(),moves:0})
export function SliderGame({onBack}:{onBack:()=>void}){const[game,setGame]=useState<State>(fresh),[best,setBest]=useState(0),[ready,setReady]=useState(false);const complete=isSolved(game.board);useEffect(()=>{void localRepository.getProgress('slider').then(saved=>{if(saved?.state)setGame(saved.state as State);setBest(Number(saved?.stats.bestMoves??0));setReady(true)})},[]);useEffect(()=>{if(!ready)return;const nextBest=complete&&(!best||game.moves<best)?game.moves:best;if(nextBest!==best)setBest(nextBest);const timer=setTimeout(()=>void localRepository.saveProgress({gameId:'slider',version:1,currentLevel:1,stars:complete?(game.moves<=180?3:game.moves<=260?2:1):0,score:0,highScore:0,stats:{moves:game.moves,bestMoves:nextBest},state:game,updatedAt:new Date().toISOString()}),120);return()=>clearTimeout(timer)},[game,best,complete,ready]);const move=(index:number)=>{const board=moveTile(game.board,index);if(board)setGame({board,moves:game.moves+1})};return <section className="slider-game" aria-label="Jogo Deslizante"><header className="game-header"><button className="icon-action" onClick={onBack} aria-label="Voltar aos jogos"><ArrowLeft/></button><div><span>Deslizante</span><strong>{game.moves} movimentos</strong></div><button className="icon-action" onClick={()=>setGame(fresh())} aria-label="Embaralhar novamente"><RotateCcw/></button></header><div className="slider-copy"><p className="eyebrow">Organize as peças</p><h1>Coloque tudo em ordem.</h1><p>Toque numa peça ao lado do espaço vazio. O embaralhamento sempre possui solução.</p><span><Trophy/> Melhor resultado: <strong>{best||'—'}</strong></span></div><div className="slider-board" role="grid" aria-label="Quebra-cabeça deslizante 4 por 4">{game.board.map((value,index)=>value?<button role="gridcell" key={value} onClick={()=>move(index)} disabled={!moveTile(game.board,index)} aria-label={`Peça ${value}`}>{value}</button>:<span role="gridcell" key="empty" aria-label="Espaço vazio"/>)}</div>{complete&&<div className="game-over" role="dialog" aria-modal="true"><div><span>Ordem restaurada</span><h2>Quebra-cabeça concluído!</h2><p>Você terminou em <strong>{game.moves} movimentos</strong>.</p><button className="primary" onClick={()=>setGame(fresh())}>Jogar novamente</button></div></div>}</section>}
