project_id = "evoria-platform"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public", "evoriplay"]

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://127.0.0.1:5173"]
