import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowRightLeft, CornerUpLeft, Hammer, RotateCcw, Trophy } from 'lucide-react'
import { localRepository } from '../../data/db'
import { COLUMN_HEIGHT, columnsFull, dropTile, emptyColumns, largestTile, nextTile, removeTop, swapTops, type Columns } from './engine'
import './columns.css'
import './columns-extra.css'
interface Snapshot { columns:Columns; current:number; upcoming:number; score:number; moves:number; bestCombo:number; hammers:number; swaps:number }
interface State extends Snapshot { previous:Snapshot|null }
type Tool='drop'|'hammer'|'swap'
const fresh=():State=>({columns:emptyColumns(),current:2,upcoming:2,score:0,moves:0,bestCombo:0,hammers:1,swaps:1,previous:null})
const label=(value:number)=>value<1000?String(value):value<1e6?`${Math.round(value/1024)}K`:value<1e9?`${Math.round(value/1048576)}M`:`${Math.round(value/1073741824)}B`
const snapshot=(state:State):Snapshot=>({columns:state.columns,current:state.current,upcoming:state.upcoming,score:state.score,moves:state.moves,bestCombo:state.bestCombo,hammers:state.hammers,swaps:state.swaps})
export function ColumnsGame({onBack}:{onBack:()=>void}){
 const[game,setGame]=useState<State>(fresh),[record,setRecord]=useState(0),[ready,setReady]=useState(false),[confirm,setConfirm]=useState(false),[tool,setTool]=useState<Tool>('drop'),[swapStart,setSwapStart]=useState<number|null>(null);const over=columnsFull(game.columns)
 useEffect(()=>{void localRepository.getProgress('columns').then(saved=>{if(saved?.state){const state=saved.state as Partial<State>;setGame({...fresh(),...state,current:state.current??2,upcoming:state.upcoming??2})}setRecord(saved?.highScore??0);setReady(true)})},[])
 useEffect(()=>{if(!ready)return;const timer=setTimeout(()=>void localRepository.saveProgress({gameId:'columns',version:2,currentLevel:1,stars:largestTile(game.columns)>=2048?3:largestTile(game.columns)>=512?2:0,score:game.score,highScore:Math.max(record,game.score),stats:{moves:game.moves,maxTile:largestTile(game.columns),bestCombo:game.bestCombo},state:game,updatedAt:new Date().toISOString()}),120);if(game.score>record)setRecord(game.score);return()=>clearTimeout(timer)},[game,record,ready])
 const drop=(column:number)=>setGame(state=>{const result=dropTile(state.columns,column,state.current);if(!result)return state;const moves=state.moves+1,maximum=largestTile(result.columns);return{...state,columns:result.columns,current:state.upcoming,upcoming:nextTile(maximum),score:state.score+state.current+result.gained*Math.max(1,result.combo),moves,bestCombo:Math.max(state.bestCombo,result.combo),hammers:state.hammers+(moves%24===0?1:0),swaps:state.swaps+(moves%36===0?1:0),previous:snapshot(state)}})
 const choose=(column:number)=>{if(tool==='drop'){drop(column);return}if(tool==='hammer'){setGame(state=>{const columns=removeTop(state.columns,column);return columns?{...state,columns,hammers:state.hammers-1,previous:snapshot(state)}:state});setTool('drop');return}if(swapStart===null){setSwapStart(column);return}setGame(state=>{const columns=swapTops(state.columns,swapStart,column);return columns?{...state,columns,swaps:state.swaps-1,previous:snapshot(state)}:state});setSwapStart(null);setTool('drop')}
 const undo=()=>setGame(state=>state.previous?{...state.previous,previous:null}:state);const restart=()=>{if(game.moves&&!confirm){setConfirm(true);setTimeout(()=>setConfirm(false),3000);return}setGame(fresh());setConfirm(false)}
 return <section className="columns-game" aria-label="Jogo Colunas"><header className="game-header"><button className="icon-action" onClick={onBack} aria-label="Voltar aos jogos"><ArrowLeft/></button><div><span>Colunas</span><strong>{game.score.toLocaleString('pt-BR')} pontos</strong></div><button className={`icon-action ${confirm?'confirming':''}`} onClick={restart} aria-label={confirm?'Confirmar nova partida':'Nova partida'}><RotateCcw/></button></header><div className="columns-summary"><span><Trophy/> Recorde <strong>{Math.max(record,game.score).toLocaleString('pt-BR')}</strong></span><span>Maior <strong>{label(largestTile(game.columns)||2)}</strong></span><button onClick={undo} disabled={!game.previous}><CornerUpLeft/> Desfazer</button></div>{confirm&&<p className="reset-warning">Toque novamente para confirmar.</p>}<div className="columns-copy"><p className="eyebrow">Queda e fusão</p><h1>Construa fusões gigantes.</h1><p>Blocos iguais conectados na vertical ou horizontal se fundem em cascata.</p></div><div className="piece-preview"><div><span>Agora</span><strong className={`number-${game.current}`}>{label(game.current)}</strong></div><div><span>Depois</span><strong className={`number-${game.upcoming}`}>{label(game.upcoming)}</strong></div></div><div className="columns-board" role="grid" aria-label="Cinco colunas numéricas">{game.columns.map((stack,column)=><button role="gridcell" key={column} disabled={tool==='drop'&&stack.length>=COLUMN_HEIGHT} onClick={()=>choose(column)} aria-label={`${tool==='drop'?`Soltar ${game.current}`:tool==='hammer'?'Remover bloco superior':swapStart===null?'Escolher primeira coluna':'Trocar blocos'} na coluna ${column+1}`}><span className="drop-hint">{tool==='drop'?'↓':tool==='hammer'?'×':'↔'}</span>{Array.from({length:COLUMN_HEIGHT},(_,visual)=>{const value=stack[COLUMN_HEIGHT-1-visual];return <i key={visual} className={value?`number-${value}`:''}>{value?label(value):''}</i>})}</button>)}</div><div className="column-tools"><button className={tool==='hammer'?'active':''} disabled={!game.hammers} onClick={()=>setTool(tool==='hammer'?'drop':'hammer')}><Hammer/> Martelo <b>{game.hammers}</b></button><button className={tool==='swap'?'active':''} disabled={!game.swaps} onClick={()=>{setTool(tool==='swap'?'drop':'swap');setSwapStart(null)}}><ArrowRightLeft/> Trocar <b>{game.swaps}</b></button></div><p className="columns-help">Ajudas são conquistadas jogando. Nenhuma compra é necessária.</p>{over&&<div className="game-over" role="dialog" aria-modal="true"><div><span>Colunas preenchidas</span><h2>Grande sequência!</h2><p>Você alcançou a peça <strong>{label(largestTile(game.columns))}</strong>.</p><button className="primary" onClick={()=>setGame(fresh())}>Jogar novamente</button></div></div>}</section>}
